export interface Airport {
  iata: string;
  city: string;
  name: string;
  country: string;
}

export const AIRPORTS: Airport[] = [
  // Europa
  { iata: 'LHR', city: 'Londra', name: 'Heathrow', country: 'GB' },
  { iata: 'LGW', city: 'Londra', name: 'Gatwick', country: 'GB' },
  { iata: 'STN', city: 'Londra', name: 'Stansted', country: 'GB' },
  { iata: 'LTN', city: 'Londra', name: 'Luton', country: 'GB' },
  { iata: 'LCY', city: 'Londra', name: 'City Airport', country: 'GB' },
  { iata: 'CDG', city: 'Parigi', name: 'Charles de Gaulle', country: 'FR' },
  { iata: 'ORY', city: 'Parigi', name: 'Orly', country: 'FR' },
  { iata: 'AMS', city: 'Amsterdam', name: 'Schiphol', country: 'NL' },
  { iata: 'FRA', city: 'Francoforte', name: 'Frankfurt', country: 'DE' },
  { iata: 'MUC', city: 'Monaco', name: 'Munich', country: 'DE' },
  { iata: 'BER', city: 'Berlino', name: 'Brandenburg', country: 'DE' },
  { iata: 'HAM', city: 'Amburgo', name: 'Hamburg', country: 'DE' },
  { iata: 'DUS', city: 'Dusseldorf', name: 'Düsseldorf', country: 'DE' },
  { iata: 'STR', city: 'Stoccarda', name: 'Stuttgart', country: 'DE' },
  { iata: 'CGN', city: 'Colonia', name: 'Cologne Bonn', country: 'DE' },
  { iata: 'MAD', city: 'Madrid', name: 'Barajas', country: 'ES' },
  { iata: 'BCN', city: 'Barcellona', name: 'El Prat', country: 'ES' },
  { iata: 'VLC', city: 'Valencia', name: 'Valencia', country: 'ES' },
  { iata: 'SVQ', city: 'Siviglia', name: 'Seville', country: 'ES' },
  { iata: 'AGP', city: 'Malaga', name: 'Costa del Sol', country: 'ES' },
  { iata: 'PMI', city: 'Palma di Maiorca', name: 'Son Sant Joan', country: 'ES' },
  { iata: 'FCO', city: 'Roma', name: 'Fiumicino', country: 'IT' },
  { iata: 'CIA', city: 'Roma', name: 'Ciampino', country: 'IT' },
  { iata: 'MXP', city: 'Milano', name: 'Malpensa', country: 'IT' },
  { iata: 'LIN', city: 'Milano', name: 'Linate', country: 'IT' },
  { iata: 'BGY', city: 'Milano', name: 'Bergamo Orio al Serio', country: 'IT' },
  { iata: 'VCE', city: 'Venezia', name: 'Marco Polo', country: 'IT' },
  { iata: 'NAP', city: 'Napoli', name: 'Capodichino', country: 'IT' },
  { iata: 'PSA', city: 'Pisa', name: 'Galileo Galilei', country: 'IT' },
  { iata: 'BLQ', city: 'Bologna', name: 'Guglielmo Marconi', country: 'IT' },
  { iata: 'CTA', city: 'Catania', name: 'Fontanarossa', country: 'IT' },
  { iata: 'PMO', city: 'Palermo', name: 'Falcone Borsellino', country: 'IT' },
  { iata: 'CAG', city: 'Cagliari', name: 'Elmas', country: 'IT' },
  { iata: 'BRI', city: 'Bari', name: 'Karol Wojtyla', country: 'IT' },
  { iata: 'LIS', city: 'Lisbona', name: 'Humberto Delgado', country: 'PT' },
  { iata: 'OPO', city: 'Porto', name: 'Francisco Sá Carneiro', country: 'PT' },
  { iata: 'FAO', city: 'Faro', name: 'Faro', country: 'PT' },
  { iata: 'VIE', city: 'Vienna', name: 'Schwechat', country: 'AT' },
  { iata: 'ZRH', city: 'Zurigo', name: 'Kloten', country: 'CH' },
  { iata: 'GVA', city: 'Ginevra', name: 'Geneva', country: 'CH' },
  { iata: 'BSL', city: 'Basilea', name: 'EuroAirport', country: 'CH' },
  { iata: 'BRU', city: 'Bruxelles', name: 'Zaventem', country: 'BE' },
  { iata: 'ARN', city: 'Stoccolma', name: 'Arlanda', country: 'SE' },
  { iata: 'CPH', city: 'Copenaghen', name: 'Kastrup', country: 'DK' },
  { iata: 'OSL', city: 'Oslo', name: 'Gardermoen', country: 'NO' },
  { iata: 'HEL', city: 'Helsinki', name: 'Vantaa', country: 'FI' },
  { iata: 'DUB', city: 'Dublino', name: 'Dublin', country: 'IE' },
  { iata: 'ATH', city: 'Atene', name: 'Eleftherios Venizelos', country: 'GR' },
  { iata: 'SKG', city: 'Salonicco', name: 'Macedonia', country: 'GR' },
  { iata: 'HER', city: 'Heraklion', name: 'Nikos Kazantzakis', country: 'GR' },
  { iata: 'RHO', city: 'Rodi', name: 'Diagoras', country: 'GR' },
  { iata: 'JTR', city: 'Santorini', name: 'Santorini', country: 'GR' },
  { iata: 'MYK', city: 'Mykonos', name: 'Mykonos', country: 'GR' },
  { iata: 'CFU', city: 'Corfù', name: 'Ioannis Kapodistrias', country: 'GR' },
  { iata: 'WAW', city: 'Varsavia', name: 'Chopin', country: 'PL' },
  { iata: 'PRG', city: 'Praga', name: 'Václav Havel', country: 'CZ' },
  { iata: 'BUD', city: 'Budapest', name: 'Ferenc Liszt', country: 'HU' },
  { iata: 'OTP', city: 'Bucarest', name: 'Henri Coandă', country: 'RO' },
  { iata: 'SOF', city: 'Sofia', name: 'Sofia', country: 'BG' },
  { iata: 'LJU', city: 'Lubiana', name: 'Jože Pučnik', country: 'SI' },
  { iata: 'ZAG', city: 'Zagabria', name: 'Zagreb', country: 'HR' },
  { iata: 'DBV', city: 'Dubrovnik', name: 'Dubrovnik', country: 'HR' },
  { iata: 'SPU', city: 'Spalato', name: 'Split', country: 'HR' },
  { iata: 'TGD', city: 'Podgorica', name: 'Podgorica', country: 'ME' },
  { iata: 'BEG', city: 'Belgrado', name: 'Nikola Tesla', country: 'RS' },
  { iata: 'SKP', city: 'Skopje', name: 'Alexander the Great', country: 'MK' },
  { iata: 'TIA', city: 'Tirana', name: 'Mother Teresa', country: 'AL' },
  { iata: 'SVO', city: 'Mosca', name: 'Sheremetyevo', country: 'RU' },
  { iata: 'DME', city: 'Mosca', name: 'Domodedovo', country: 'RU' },
  { iata: 'LED', city: 'San Pietroburgo', name: 'Pulkovo', country: 'RU' },
  { iata: 'KBP', city: 'Kiev', name: 'Boryspil', country: 'UA' },
  { iata: 'MAN', city: 'Manchester', name: 'Manchester', country: 'GB' },
  { iata: 'EDI', city: 'Edimburgo', name: 'Edinburgh', country: 'GB' },
  { iata: 'GLA', city: 'Glasgow', name: 'Glasgow', country: 'GB' },
  { iata: 'BHX', city: 'Birmingham', name: 'Birmingham', country: 'GB' },
  { iata: 'BRS', city: 'Bristol', name: 'Bristol', country: 'GB' },
  { iata: 'NCE', city: 'Nizza', name: 'Côte d\'Azur', country: 'FR' },
  { iata: 'MRS', city: 'Marsiglia', name: 'Provence', country: 'FR' },
  { iata: 'LYS', city: 'Lione', name: 'Saint-Exupéry', country: 'FR' },
  { iata: 'TLS', city: 'Tolosa', name: 'Blagnac', country: 'FR' },
  { iata: 'BOD', city: 'Bordeaux', name: 'Mérignac', country: 'FR' },
  { iata: 'NTE', city: 'Nantes', name: 'Atlantique', country: 'FR' },
  { iata: 'REK', city: 'Reykjavik', name: 'Keflavik', country: 'IS' },
  { iata: 'KEF', city: 'Reykjavik', name: 'Keflavik', country: 'IS' },
  { iata: 'VRN', city: 'Verona', name: 'Catullo', country: 'IT' },
  { iata: 'TRN', city: 'Torino', name: 'Caselle', country: 'IT' },
  { iata: 'GEN', city: 'Genova', name: 'Cristoforo Colombo', country: 'IT' },
  { iata: 'FLR', city: 'Firenze', name: 'Peretola', country: 'IT' },
  { iata: 'AHO', city: 'Alghero', name: 'Riviera del Corallo', country: 'IT' },
  { iata: 'OLB', city: 'Olbia', name: 'Costa Smeralda', country: 'IT' },
  { iata: 'REG', city: 'Reggio Calabria', name: 'Tito Minniti', country: 'IT' },
  // Medio Oriente
  { iata: 'DXB', city: 'Dubai', name: 'Dubai International', country: 'AE' },
  { iata: 'DWC', city: 'Dubai', name: 'Al Maktoum', country: 'AE' },
  { iata: 'AUH', city: 'Abu Dhabi', name: 'Zayed International', country: 'AE' },
  { iata: 'DOH', city: 'Doha', name: 'Hamad International', country: 'QA' },
  { iata: 'RUH', city: 'Riyadh', name: 'King Khalid', country: 'SA' },
  { iata: 'JED', city: 'Jeddah', name: 'King Abdulaziz', country: 'SA' },
  { iata: 'KWI', city: 'Kuwait City', name: 'Kuwait International', country: 'KW' },
  { iata: 'BAH', city: 'Manama', name: 'Bahrain International', country: 'BH' },
  { iata: 'MCT', city: 'Muscat', name: 'Muscat International', country: 'OM' },
  { iata: 'TLV', city: 'Tel Aviv', name: 'Ben Gurion', country: 'IL' },
  { iata: 'AMM', city: 'Amman', name: 'Queen Alia', country: 'JO' },
  { iata: 'BEY', city: 'Beirut', name: 'Rafic Hariri', country: 'LB' },
  { iata: 'IST', city: 'Istanbul', name: 'Istanbul Airport', country: 'TR' },
  { iata: 'SAW', city: 'Istanbul', name: 'Sabiha Gökçen', country: 'TR' },
  { iata: 'ESB', city: 'Ankara', name: 'Esenboğa', country: 'TR' },
  { iata: 'AYT', city: 'Antalya', name: 'Antalya', country: 'TR' },
  { iata: 'ADB', city: 'Izmir', name: 'Adnan Menderes', country: 'TR' },
  // Asia
  { iata: 'NRT', city: 'Tokyo', name: 'Narita', country: 'JP' },
  { iata: 'HND', city: 'Tokyo', name: 'Haneda', country: 'JP' },
  { iata: 'KIX', city: 'Osaka', name: 'Kansai', country: 'JP' },
  { iata: 'ITM', city: 'Osaka', name: 'Itami', country: 'JP' },
  { iata: 'NGO', city: 'Nagoya', name: 'Chubu Centrair', country: 'JP' },
  { iata: 'CTS', city: 'Sapporo', name: 'New Chitose', country: 'JP' },
  { iata: 'OKA', city: 'Okinawa', name: 'Naha', country: 'JP' },
  { iata: 'FUK', city: 'Fukuoka', name: 'Fukuoka', country: 'JP' },
  { iata: 'HIJ', city: 'Hiroshima', name: 'Hiroshima', country: 'JP' },
  { iata: 'ICN', city: 'Seoul', name: 'Incheon', country: 'KR' },
  { iata: 'GMP', city: 'Seoul', name: 'Gimpo', country: 'KR' },
  { iata: 'PUS', city: 'Busan', name: 'Gimhae', country: 'KR' },
  { iata: 'PEK', city: 'Pechino', name: 'Capital', country: 'CN' },
  { iata: 'PKX', city: 'Pechino', name: 'Daxing', country: 'CN' },
  { iata: 'PVG', city: 'Shanghai', name: 'Pudong', country: 'CN' },
  { iata: 'SHA', city: 'Shanghai', name: 'Hongqiao', country: 'CN' },
  { iata: 'CAN', city: 'Canton', name: 'Baiyun', country: 'CN' },
  { iata: 'CTU', city: 'Chengdu', name: 'Tianfu', country: 'CN' },
  { iata: 'HKG', city: 'Hong Kong', name: 'Hong Kong International', country: 'HK' },
  { iata: 'MFM', city: 'Macao', name: 'Macao International', country: 'MO' },
  { iata: 'TPE', city: 'Taipei', name: 'Taoyuan', country: 'TW' },
  { iata: 'SIN', city: 'Singapore', name: 'Changi', country: 'SG' },
  { iata: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi', country: 'TH' },
  { iata: 'DMK', city: 'Bangkok', name: 'Don Mueang', country: 'TH' },
  { iata: 'HKT', city: 'Phuket', name: 'Phuket', country: 'TH' },
  { iata: 'CNX', city: 'Chiang Mai', name: 'Chiang Mai', country: 'TH' },
  { iata: 'KUL', city: 'Kuala Lumpur', name: 'KLIA', country: 'MY' },
  { iata: 'CGK', city: 'Giacarta', name: 'Soekarno-Hatta', country: 'ID' },
  { iata: 'DPS', city: 'Bali', name: 'Ngurah Rai', country: 'ID' },
  { iata: 'SUB', city: 'Surabaya', name: 'Juanda', country: 'ID' },
  { iata: 'MNL', city: 'Manila', name: 'Ninoy Aquino', country: 'PH' },
  { iata: 'CEB', city: 'Cebu', name: 'Mactan-Cebu', country: 'PH' },
  { iata: 'HAN', city: 'Hanoi', name: 'Noi Bai', country: 'VN' },
  { iata: 'SGN', city: 'Ho Chi Minh', name: 'Tan Son Nhat', country: 'VN' },
  { iata: 'DAD', city: 'Da Nang', name: 'Da Nang', country: 'VN' },
  { iata: 'PNH', city: 'Phnom Penh', name: 'Phnom Penh', country: 'KH' },
  { iata: 'REP', city: 'Siem Reap', name: 'Siem Reap', country: 'KH' },
  { iata: 'RGN', city: 'Yangon', name: 'Yangon', country: 'MM' },
  { iata: 'BOM', city: 'Mumbai', name: 'Chhatrapati Shivaji', country: 'IN' },
  { iata: 'DEL', city: 'Delhi', name: 'Indira Gandhi', country: 'IN' },
  { iata: 'BLR', city: 'Bangalore', name: 'Kempegowda', country: 'IN' },
  { iata: 'MAA', city: 'Chennai', name: 'Chennai', country: 'IN' },
  { iata: 'CCU', city: 'Calcutta', name: 'Netaji Subhas Chandra Bose', country: 'IN' },
  { iata: 'HYD', city: 'Hyderabad', name: 'Rajiv Gandhi', country: 'IN' },
  { iata: 'GOI', city: 'Goa', name: 'Dabolim', country: 'IN' },
  { iata: 'CMB', city: 'Colombo', name: 'Bandaranaike', country: 'LK' },
  { iata: 'KTM', city: 'Kathmandu', name: 'Tribhuvan', country: 'NP' },
  { iata: 'DAC', city: 'Dhaka', name: 'Hazrat Shahjalal', country: 'BD' },
  { iata: 'KHI', city: 'Karachi', name: 'Jinnah', country: 'PK' },
  { iata: 'LHE', city: 'Lahore', name: 'Allama Iqbal', country: 'PK' },
  { iata: 'ISB', city: 'Islamabad', name: 'New Islamabad', country: 'PK' },
  { iata: 'ULN', city: 'Ulaanbaatar', name: 'Chinggis Khaan', country: 'MN' },
  // Africa
  { iata: 'JNB', city: 'Johannesburg', name: 'O.R. Tambo', country: 'ZA' },
  { iata: 'CPT', city: 'Città del Capo', name: 'Cape Town', country: 'ZA' },
  { iata: 'DUR', city: 'Durban', name: 'King Shaka', country: 'ZA' },
  { iata: 'CAI', city: 'Il Cairo', name: 'Cairo', country: 'EG' },
  { iata: 'HRG', city: 'Hurghada', name: 'Hurghada', country: 'EG' },
  { iata: 'SSH', city: 'Sharm el-Sheikh', name: 'Sharm el-Sheikh', country: 'EG' },
  { iata: 'CMN', city: 'Casablanca', name: 'Mohammed V', country: 'MA' },
  { iata: 'RAK', city: 'Marrakech', name: 'Menara', country: 'MA' },
  { iata: 'FEZ', city: 'Fez', name: 'Saïss', country: 'MA' },
  { iata: 'TNG', city: 'Tangeri', name: 'Ibn Battouta', country: 'MA' },
  { iata: 'ALG', city: 'Algeri', name: 'Houari Boumediene', country: 'DZ' },
  { iata: 'TUN', city: 'Tunisi', name: 'Carthage', country: 'TN' },
  { iata: 'TRI', city: 'Tripoli', name: 'Mitiga', country: 'LY' },
  { iata: 'ADD', city: 'Addis Abeba', name: 'Bole', country: 'ET' },
  { iata: 'NBO', city: 'Nairobi', name: 'Jomo Kenyatta', country: 'KE' },
  { iata: 'MBA', city: 'Mombasa', name: 'Moi', country: 'KE' },
  { iata: 'DAR', city: 'Dar es Salaam', name: 'Julius Nyerere', country: 'TZ' },
  { iata: 'JRO', city: 'Kilimanjaro', name: 'Kilimanjaro', country: 'TZ' },
  { iata: 'ZNZ', city: 'Zanzibar', name: 'Abeid Amani Karume', country: 'TZ' },
  { iata: 'EBB', city: 'Kampala', name: 'Entebbe', country: 'UG' },
  { iata: 'LOS', city: 'Lagos', name: 'Murtala Muhammed', country: 'NG' },
  { iata: 'ABV', city: 'Abuja', name: 'Nnamdi Azikiwe', country: 'NG' },
  { iata: 'ACC', city: 'Accra', name: 'Kotoka', country: 'GH' },
  { iata: 'ABJ', city: 'Abidjan', name: 'Félix-Houphouët-Boigny', country: 'CI' },
  { iata: 'DKR', city: 'Dakar', name: 'Blaise Diagne', country: 'SN' },
  { iata: 'TNR', city: 'Antananarivo', name: 'Ivato', country: 'MG' },
  { iata: 'MRU', city: 'Mauritius', name: 'Sir Seewoosagur Ramgoolam', country: 'MU' },
  { iata: 'SEZ', city: 'Seychelles', name: 'Seychelles', country: 'SC' },
  // Americhe
  { iata: 'JFK', city: 'New York', name: 'John F. Kennedy', country: 'US' },
  { iata: 'LGA', city: 'New York', name: 'LaGuardia', country: 'US' },
  { iata: 'EWR', city: 'New York', name: 'Newark', country: 'US' },
  { iata: 'LAX', city: 'Los Angeles', name: 'Los Angeles', country: 'US' },
  { iata: 'ORD', city: 'Chicago', name: "O'Hare", country: 'US' },
  { iata: 'MDW', city: 'Chicago', name: 'Midway', country: 'US' },
  { iata: 'ATL', city: 'Atlanta', name: 'Hartsfield-Jackson', country: 'US' },
  { iata: 'DFW', city: 'Dallas', name: 'Dallas/Fort Worth', country: 'US' },
  { iata: 'DEN', city: 'Denver', name: 'Denver', country: 'US' },
  { iata: 'SFO', city: 'San Francisco', name: 'San Francisco', country: 'US' },
  { iata: 'SEA', city: 'Seattle', name: 'Seattle-Tacoma', country: 'US' },
  { iata: 'MIA', city: 'Miami', name: 'Miami', country: 'US' },
  { iata: 'BOS', city: 'Boston', name: 'Logan', country: 'US' },
  { iata: 'PHX', city: 'Phoenix', name: 'Sky Harbor', country: 'US' },
  { iata: 'MCO', city: 'Orlando', name: 'Orlando', country: 'US' },
  { iata: 'IAH', city: 'Houston', name: 'George Bush', country: 'US' },
  { iata: 'HOU', city: 'Houston', name: 'Hobby', country: 'US' },
  { iata: 'LAS', city: 'Las Vegas', name: 'Harry Reid', country: 'US' },
  { iata: 'CLT', city: 'Charlotte', name: 'Douglas', country: 'US' },
  { iata: 'MSP', city: 'Minneapolis', name: 'Minneapolis-Saint Paul', country: 'US' },
  { iata: 'DTW', city: 'Detroit', name: 'Detroit Metro', country: 'US' },
  { iata: 'PHL', city: 'Philadelphia', name: 'Philadelphia', country: 'US' },
  { iata: 'SLC', city: 'Salt Lake City', name: 'Salt Lake City', country: 'US' },
  { iata: 'FLL', city: 'Fort Lauderdale', name: 'Fort Lauderdale', country: 'US' },
  { iata: 'DCA', city: 'Washington', name: 'Reagan', country: 'US' },
  { iata: 'IAD', city: 'Washington', name: 'Dulles', country: 'US' },
  { iata: 'BWI', city: 'Baltimora', name: 'Baltimore/Washington', country: 'US' },
  { iata: 'SAN', city: 'San Diego', name: 'San Diego', country: 'US' },
  { iata: 'PDX', city: 'Portland', name: 'Portland', country: 'US' },
  { iata: 'HNL', city: 'Honolulu', name: 'Daniel K. Inouye', country: 'US' },
  { iata: 'AUS', city: 'Austin', name: 'Austin-Bergstrom', country: 'US' },
  { iata: 'MSY', city: 'New Orleans', name: 'Louis Armstrong', country: 'US' },
  { iata: 'BNA', city: 'Nashville', name: 'Nashville', country: 'US' },
  { iata: 'RDU', city: 'Raleigh-Durham', name: 'Raleigh-Durham', country: 'US' },
  { iata: 'STL', city: 'St. Louis', name: 'Lambert', country: 'US' },
  { iata: 'MCI', city: 'Kansas City', name: 'Kansas City', country: 'US' },
  { iata: 'YYZ', city: 'Toronto', name: 'Pearson', country: 'CA' },
  { iata: 'YVR', city: 'Vancouver', name: 'Vancouver', country: 'CA' },
  { iata: 'YUL', city: 'Montreal', name: 'Trudeau', country: 'CA' },
  { iata: 'YYC', city: 'Calgary', name: 'Calgary', country: 'CA' },
  { iata: 'YEG', city: 'Edmonton', name: 'Edmonton', country: 'CA' },
  { iata: 'YOW', city: 'Ottawa', name: 'Ottawa', country: 'CA' },
  { iata: 'GRU', city: 'São Paulo', name: 'Guarulhos', country: 'BR' },
  { iata: 'GIG', city: 'Rio de Janeiro', name: 'Galeão', country: 'BR' },
  { iata: 'SDU', city: 'Rio de Janeiro', name: 'Santos Dumont', country: 'BR' },
  { iata: 'BSB', city: 'Brasilia', name: 'Brasilia', country: 'BR' },
  { iata: 'SSA', city: 'Salvador', name: 'Deputado Luís Eduardo Magalhães', country: 'BR' },
  { iata: 'FOR', city: 'Fortaleza', name: 'Pinto Martins', country: 'BR' },
  { iata: 'REC', city: 'Recife', name: 'Guararapes', country: 'BR' },
  { iata: 'EZE', city: 'Buenos Aires', name: 'Ezeiza', country: 'AR' },
  { iata: 'AEP', city: 'Buenos Aires', name: 'Jorge Newbery', country: 'AR' },
  { iata: 'COR', city: 'Córdoba', name: 'Ambrosio Taravella', country: 'AR' },
  { iata: 'SCL', city: 'Santiago', name: 'Arturo Merino Benítez', country: 'CL' },
  { iata: 'BOG', city: 'Bogotà', name: 'El Dorado', country: 'CO' },
  { iata: 'MDE', city: 'Medellín', name: 'José María Córdova', country: 'CO' },
  { iata: 'LIM', city: 'Lima', name: 'Jorge Chávez', country: 'PE' },
  { iata: 'UIO', city: 'Quito', name: 'Mariscal Sucre', country: 'EC' },
  { iata: 'GYE', city: 'Guayaquil', name: 'José Joaquín de Olmedo', country: 'EC' },
  { iata: 'VVI', city: 'Santa Cruz', name: 'Viru Viru', country: 'BO' },
  { iata: 'ASU', city: 'Asuncion', name: 'Silvio Pettirossi', country: 'PY' },
  { iata: 'MVD', city: 'Montevideo', name: 'Carrasco', country: 'UY' },
  { iata: 'MEX', city: 'Città del Messico', name: 'Benito Juárez', country: 'MX' },
  { iata: 'CUN', city: 'Cancún', name: 'Cancún', country: 'MX' },
  { iata: 'GDL', city: 'Guadalajara', name: 'Miguel Hidalgo', country: 'MX' },
  { iata: 'MTY', city: 'Monterrey', name: 'General Mariano Escobedo', country: 'MX' },
  { iata: 'PTY', city: 'Panama City', name: 'Tocumen', country: 'PA' },
  { iata: 'SJO', city: 'San José', name: 'Juan Santamaría', country: 'CR' },
  { iata: 'HAV', city: 'L\'Avana', name: 'José Martí', country: 'CU' },
  { iata: 'SDQ', city: 'Santo Domingo', name: 'Las Américas', country: 'DO' },
  { iata: 'PUJ', city: 'Punta Cana', name: 'Punta Cana', country: 'DO' },
  { iata: 'MBJ', city: 'Montego Bay', name: 'Sangster', country: 'JM' },
  { iata: 'NAS', city: 'Nassau', name: 'Lynden Pindling', country: 'BS' },
  // Oceania
  { iata: 'SYD', city: 'Sydney', name: 'Kingsford Smith', country: 'AU' },
  { iata: 'MEL', city: 'Melbourne', name: 'Tullamarine', country: 'AU' },
  { iata: 'BNE', city: 'Brisbane', name: 'Brisbane', country: 'AU' },
  { iata: 'PER', city: 'Perth', name: 'Perth', country: 'AU' },
  { iata: 'ADL', city: 'Adelaide', name: 'Adelaide', country: 'AU' },
  { iata: 'CBR', city: 'Canberra', name: 'Canberra', country: 'AU' },
  { iata: 'CNS', city: 'Cairns', name: 'Cairns', country: 'AU' },
  { iata: 'OOL', city: 'Gold Coast', name: 'Gold Coast', country: 'AU' },
  { iata: 'AKL', city: 'Auckland', name: 'Auckland', country: 'NZ' },
  { iata: 'CHC', city: 'Christchurch', name: 'Christchurch', country: 'NZ' },
  { iata: 'WLG', city: 'Wellington', name: 'Wellington', country: 'NZ' },
  { iata: 'NAN', city: 'Nadi', name: 'Nadi', country: 'FJ' },
  { iata: 'PPT', city: 'Papeete', name: 'Faa\'a', country: 'PF' },
  { iata: 'HNL', city: 'Honolulu', name: 'Daniel K. Inouye', country: 'US' },
  { iata: 'PPG', city: 'Pago Pago', name: 'Pago Pago', country: 'AS' },
];

export function filterAirports(query: string): Airport[] {
  if (!query || query.length < 2) return [];
  const q = query.toUpperCase().trim();
  return AIRPORTS.filter(a =>
    a.iata.startsWith(q) ||
    a.city.toUpperCase().includes(q) ||
    a.name.toUpperCase().includes(q) ||
    a.country === q
  ).slice(0, 6);
}
